global:
  application_name: covid19map
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 7.0 running on 64bit Amazon Linux/2.9.3
  default_ec2_keyname: covid19map
  default_region: us-west-2
  sc: git
